name: File upload
on: workflow_dispatch
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dest-files
          path: images/aws.png
      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: dest-files
      